[pytest]
testpaths = tests .
addopts = -v -ra --tb=short
norecursedirs = 
    template_vite 
    android 
    env 
    venv 
    build 
    dist 
    node_modules 
    */main/assets/python

asyncio_mode = auto
