import ast
import os
import re
from pathlib import Path
from typing import List, Set
from ..console import log


class VirtualRootGenerator:
    """
    Scans the codebase for 'app.expose' and generates a
    Virtual Entry Point (VEP) that acts as the minimal root for the dependency graph.
    """

    def __init__(self, source_dir: Path):
        self.source_dir = source_dir
        self.exposed_functions = []  # List of (module_name, function_name)
        self.discovered_modules = set()

    def scan(self):
        """
        Recursively scans .py files for app.expose usages.
        """
        log("Scanning for exposed API endpoints...", style="cyan")

        for root, _, files in os.walk(self.source_dir):
            for file in files:
                if file.endswith(".py") and not file.startswith("_"):
                    full_path = Path(root) / file
                    self._scan_file(full_path)

        log(
            f"Found {len(self.exposed_functions)} exposed endpoints across {len(self.discovered_modules)} modules.",
            style="info",
        )

    def _scan_file(self, file_path: Path):
        try:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
            tree = ast.parse(content)

            # Calculate module name
            rel_path = file_path.relative_to(self.source_dir)
            module_parts = list(rel_path.parts)
            module_parts[-1] = module_parts[-1].replace(".py", "")
            if module_parts[-1] == "__init__":
                module_parts.pop()
            module_name = ".".join(module_parts)

            self.discovered_modules.add(module_name)

            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef):
                    is_exposed = False
                    for dec in node.decorator_list:
                        # Handle @app.expose
                        if isinstance(dec, ast.Attribute) and dec.attr == "expose":
                            is_exposed = True
                        # Handle @expose
                        elif isinstance(dec, ast.Name) and dec.id == "expose":
                            is_exposed = True
                        # Handle @app.expose(...) or @expose(...)
                        elif isinstance(dec, ast.Call):
                            if (
                                isinstance(dec.func, ast.Attribute)
                                and dec.func.attr == "expose"
                            ):
                                is_exposed = True
                            elif (
                                isinstance(dec.func, ast.Name)
                                and dec.func.id == "expose"
                            ):
                                is_exposed = True

                    if is_exposed:
                        self.exposed_functions.append((module_name, node.name))

                elif isinstance(node, ast.Call):
                    if (
                        isinstance(node.func, ast.Attribute)
                        and node.func.attr == "expose"
                    ):
                        if node.args:
                            arg = node.args[0]
                            if isinstance(arg, ast.Name):
                                self.exposed_functions.append((module_name, arg.id))
        except Exception:
            pass

    def generate(self, output_path: Path) -> Path:
        """
        Generates the _virtual_root.py file.
        Aggressively imports everything exposed to trigger the deepest dependency graph.
        """
        lines = [
            "# VIRTUAL ENTRY POINT generated by Pytron Crystal 2.0",
            "# This file forces the loading of all exposed logic and its dependencies.",
            "",
            "import sys",
            "import os",
            "import pytron",
            "",
            "print('[Shield] Loading Virtual Entry Point...')",
            "",
            "# --- EXPOSED ENDPOINTS ---",
        ]

        self.exposed_functions.sort()

        # We also import the modules themselves to ensure module-level side-effects
        # (like dynamic imports in __init__.py) are triggered.
        for mod in sorted(list(self.discovered_modules)):
            lines.append(f"try: import {mod}")
            lines.append(f"except Exception: pass")

        lines.append("\n# --- EXPOSED FUNCTIONS ---")
        for mod, func in self.exposed_functions:
            lines.append(f"try: from {mod} import {func}")
            lines.append(f"except Exception: pass")

        lines.append("")
        lines.append("def main():")
        lines.append("    print('[Shield] Virtual Root Active.')")
        lines.append("    return 0")
        lines.append("")
        lines.append("if __name__ == '__main__':")
        lines.append("    sys.exit(main())")

        output_path.write_text("\n".join(lines), encoding="utf-8")
        log(f"Generated Virtual Entry Point: {output_path.name}", style="success")
        return output_path
