// Auto-generated by Pytron. Do not edit manually.
// This file provides type definitions for the Pytron client.

declare module 'pytron-client' {

  export interface PytronClient {
    /**
     * Local state cache synchronized with the backend.
     */
    state: Record<string, any>;

    /**
     * Listen for an event sent from the Python backend.
     */
    on(event: string, callback: (data: any) => void): void;

    /**
     * Remove an event listener.
     */
    off(event: string, callback: (data: any) => void): void;

    /**
     * Wait for the backend to be connected.
     */
    waitForBackend(timeout?: number): Promise<void>;

    /**
     * Log a message to the Python console.
     */
    log(message: string): Promise<void>;

    /**
     * Opens a URL or file path in the default system browser/handler.
     */
    shell_open_external(url: string): Promise<any>;
    /**
     * Opens the folder containing the file and selects it.
     */
    shell_show_item_in_folder(path: string): Promise<any>;
    /**
     * Copies text to the system clipboard.
     */
    clipboard_write_text(text: string): Promise<any>;
    /**
     * Returns text from the system clipboard.
     */
    clipboard_read_text(): Promise<any>;
    /**
     * Returns hardware and OS information.
     */
    system_get_info(): Promise<any>;
    /**
     * Sets a value in the persistent store.
     */
    store_set(key: any, value: any): Promise<any>;
    /**
     * Gets a value from the persistent store.
     */
    store_get(key: any, default: any): Promise<any>;
    /**
     * Removes a key from the persistent store.
     */
    store_delete(key: any): Promise<any>;
    app_quit(): Promise<any>;
    app_show(): Promise<any>;
    app_hide(): Promise<any>;
    app_is_visible(): Promise<any>;
    /**
     * Broadcasts an event to all open windows.
     * This enables simple cross-window communication.
     */
    app_publish(event_name: string, data: any): Promise<any>;
    /**
     * Checks for application updates.
     * Returns update info if available, else None.
     */
    app_check_updates(url: string): Promise<any>;
    /**
     * Downloads and installs an update.
     * Emits 'pytron:update-progress' events.
     */
    app_install_update(update_info: Record<string, any>): Promise<any>;
    /**
     * Toggles the Pytron Inspector window.
     */
    app_toggle_inspector(): Promise<any>;
    minimize(): Promise<any>;
    toggle_maximize(): Promise<any>;
    /**
     * Closes the window.
     * If 'close_to_tray' config is True and force is False, it just hides the window.
     */
    close(force: any): Promise<any>;
    hide(): Promise<any>;
    show(): Promise<any>;
    start_drag(): Promise<any>;
    set_title(title: any): Promise<any>;
    set_size(w: any, h: any): Promise<any>;
    center(): Promise<any>;
    system_notification(title: any, message: any, icon: any): Promise<any>;
    set_bounds(x: any, y: any, width: any, height: any): Promise<any>;
    trigger_shortcut(combo: string): Promise<boolean>;
    get_registered_shortcuts(): Promise<string[]>;
  }

  const pytron: PytronClient;
  export default pytron;
}