name: Lint

on:
  push:
    branches: ["**"]
    paths:
      - 'pytron/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    branches: ["**"]
    paths:
      - 'pytron/**'
      - 'tests/**'
      - 'pyproject.toml'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Ruff
        run: |
          pip install ruff
      - name: Lint with Ruff
        run: |
          ruff check .
